age1 = int(input("Enter age of the first person: "))
age2 = int(input("Enter age of the second person: "))
if age1 > age2: print("the older is :" , age1)
elif age2 > age1: print("the older is :" , age2)
else: print("both are the same age")